- hosts: student-vm
  become: yes

  tasks:

    - name: Ensure user exists
      user:
        name: user
        shell: /bin/bash
        create_home: yes
        password: "{{ 'user' | password_hash('sha512') }}"

    - name: Install SSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Enable password SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
        enabled: yes

    - name: Create lab folder
      file:
        path: /home/user/lab
        state: directory
        owner: user
        group: user
        mode: '0755'


    # =========================
    # TEST API IP
    # =========================

    - name: Test API 192.168.122.1
      uri:
        url: "http://192.168.122.1:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test1
      ignore_errors: yes

    - name: Show result 1
      debug:
        var: test1


    - name: Test API 192.168.65.79
      uri:
        url: "http://192.168.65.79:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test2
      ignore_errors: yes

    - name: Show result 2
      debug:
        var: test2


    - name: Test API 192.168.130.86
      uri:
        url: "http://192.168.130.86:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test3
      ignore_errors: yes

    - name: Show result 3
      debug:
        var: test3
