- hosts: student-vm
  become: yes

  tasks:

    - name: PLAYBOOK START
      shell: echo PLAYBOOK_RUNNING_ABC


    # =========================
    # USER + SSH
    # =========================

    - name: Ensure user exists
      user:
        name: user
        shell: /bin/bash
        create_home: yes
        password: "{{ 'user' | password_hash('sha512') }}"

    - name: Install SSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Enable password SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
        enabled: yes


    # =========================
    # CREATE LAB
    # =========================

    - name: Create lab folder
      file:
        path: /home/user/lab
        state: directory
        owner: user
        group: user
        mode: '0755'


    # =========================
    # SHOW IP
    # =========================

    - name: Show IP
      shell: ip a
      register: ip_result

    - name: Print IP
      shell: echo "{{ ip_result.stdout }}"


    # =========================
    # SHOW ROUTE
    # =========================

    - name: Show route
      shell: ip route
      register: route_result

    - name: Print route
      shell: echo "{{ route_result.stdout }}"


    # =========================
    # TEST API IP
    # =========================

    - name: Test API 192.168.122.1
      uri:
        url: "http://192.168.122.1:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test1
      ignore_errors: yes

    - name: Result 1
      shell: echo RESULT1 {{ test1.failed }}


    - name: Test API 192.168.65.79
      uri:
        url: "http://192.168.65.79:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test2
      ignore_errors: yes

    - name: Result 2
      shell: echo RESULT2 {{ test2.failed }}


    - name: Test API 192.168.130.86
      uri:
        url: "http://192.168.130.86:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test3
      ignore_errors: yes

    - name: Result 3
      shell: echo RESULT3 {{ test3.failed }}


    - name: Test API 10.10.10.1
      uri:
        url: "http://10.10.10.1:5000/flag/user"
        method: GET
        return_content: yes
        timeout: 5
      register: test4
      ignore_errors: yes

    - name: Result 4
      shell: echo RESULT4 {{ test4.failed }}
